# Generated by Django 3.1.2 on 2020-10-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201003_0530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('can_put_sale', 'Put product in sale'),)},
        ),
    ]
